excluded_blocks:
- SLIME_BLOCK
- CAULDRON
- BREWING_STAND
- PISTON_MOVING_PIECE
- PISTON_STICKY_BASE
- PISTON_BASE
- HOPPER
- COBBLESTONE_STAIRS
- OAK_STAIRS
- BRICK_STAIRS
- STONE_BRICK_STAIRS
- NETHER_BRICK_STAIRS
- SANDSTONE_STAIRS
- SPRUCE_STAIRS
- BIRCH_STAIRS
- JUNGLE_STAIRS
- QUARTZ_STAIRS
- ACACIA_STAIRS
- DARK_OAK_STAIRS
- RED_SANDSTONE_STAIRS
