# 
# The message sent to players with Phase alerts on.
settings:
  EnableCustomLog: true
  CustomLogFormat: '[%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS %4$s]: %5$s%6$s%n'
  bans: 9
  testmode: false
  prefix: '&8[&c&lAntiCheat&8] '
  bancmd: ban %player% [AntiCheat] Unfair Advantage!
  broadcastmsg: '&c&lAntiCheat &7has detected &c%player% &7to be cheating and has
    been removed from the network.'
  broadcastResetViolationsMsg: true
  violationResetTime: 60
  resetViolationsAutomatically: true
  latency:
    ping: 300
    tps: 17
alerts:
  primary: '&7'
  secondary: '&c'
  checkColor: '&b'
excluded_blocks:
- SLIME_BLOCK
- CAULDRON
- BREWING_STAND
- PISTON_MOVING_PIECE
- PISTON_STICKY_BASE
- PISTON_BASE
- HOPPER
- COBBLESTONE_STAIRS
- OAK_STAIRS
- BRICK_STAIRS
- STONE_BRICK_STAIRS
- NETHER_BRICK_STAIRS
- SANDSTONE_STAIRS
- SPRUCE_STAIRS
- BIRCH_STAIRS
- JUNGLE_STAIRS
- QUARTZ_STAIRS
- ACACIA_STAIRS
- DARK_OAK_STAIRS
- RED_SANDSTONE_STAIRS
alert_message: '&8[&4!&8] &c%player% &7was caught phasing/vclipping.'
max_move: 10
